// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ANIMATION2DCOMPONENTSCHEMA_LEADERENGINE_H_
#define FLATBUFFERS_GENERATED_ANIMATION2DCOMPONENTSCHEMA_LEADERENGINE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace LeaderEngine {

struct Animation2DComponentSchema;
struct Animation2DComponentSchemaBuilder;

struct Animation2DComponentSchema FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Animation2DComponentSchemaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ANIMATION_NAME = 4,
    VT_SHOULD_LOOP = 6
  };
  const ::flatbuffers::String *animation_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ANIMATION_NAME);
  }
  bool should_loop() const {
    return GetField<uint8_t>(VT_SHOULD_LOOP, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ANIMATION_NAME) &&
           verifier.VerifyString(animation_name()) &&
           VerifyField<uint8_t>(verifier, VT_SHOULD_LOOP, 1) &&
           verifier.EndTable();
  }
};

struct Animation2DComponentSchemaBuilder {
  typedef Animation2DComponentSchema Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_animation_name(::flatbuffers::Offset<::flatbuffers::String> animation_name) {
    fbb_.AddOffset(Animation2DComponentSchema::VT_ANIMATION_NAME, animation_name);
  }
  void add_should_loop(bool should_loop) {
    fbb_.AddElement<uint8_t>(Animation2DComponentSchema::VT_SHOULD_LOOP, static_cast<uint8_t>(should_loop), 0);
  }
  explicit Animation2DComponentSchemaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Animation2DComponentSchema> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Animation2DComponentSchema>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Animation2DComponentSchema> CreateAnimation2DComponentSchema(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> animation_name = 0,
    bool should_loop = false) {
  Animation2DComponentSchemaBuilder builder_(_fbb);
  builder_.add_animation_name(animation_name);
  builder_.add_should_loop(should_loop);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Animation2DComponentSchema> CreateAnimation2DComponentSchemaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *animation_name = nullptr,
    bool should_loop = false) {
  auto animation_name__ = animation_name ? _fbb.CreateString(animation_name) : 0;
  return LeaderEngine::CreateAnimation2DComponentSchema(
      _fbb,
      animation_name__,
      should_loop);
}

inline const LeaderEngine::Animation2DComponentSchema *GetAnimation2DComponentSchema(const void *buf) {
  return ::flatbuffers::GetRoot<LeaderEngine::Animation2DComponentSchema>(buf);
}

inline const LeaderEngine::Animation2DComponentSchema *GetSizePrefixedAnimation2DComponentSchema(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<LeaderEngine::Animation2DComponentSchema>(buf);
}

inline bool VerifyAnimation2DComponentSchemaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<LeaderEngine::Animation2DComponentSchema>(nullptr);
}

inline bool VerifySizePrefixedAnimation2DComponentSchemaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<LeaderEngine::Animation2DComponentSchema>(nullptr);
}

inline void FinishAnimation2DComponentSchemaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LeaderEngine::Animation2DComponentSchema> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAnimation2DComponentSchemaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LeaderEngine::Animation2DComponentSchema> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace LeaderEngine

#endif  // FLATBUFFERS_GENERATED_ANIMATION2DCOMPONENTSCHEMA_LEADERENGINE_H_
