local EManager = EntityManager:GetInstance()
EManager:CreateEntity("Player")
local player = EManager:GetEntity("Player")
local fighter = Sprite2DComponent()
local fighterCollider = BoxColliderComponent(Vector2f(64,64))
local RManager = ResourceManager:GetInstance()
fighter:SetSprite(RManager:GetTexture("Fighter"))
player:AddComponent(fighter)
player:AddComponent(fighterCollider)
player:SetPosition(200,200)
