// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SPRITE2DCOMPONENTSCHEMA_LEADERENGINE_H_
#define FLATBUFFERS_GENERATED_SPRITE2DCOMPONENTSCHEMA_LEADERENGINE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace LeaderEngine {

struct Sprite2DComponentSchema;
struct Sprite2DComponentSchemaBuilder;

struct Sprite2DComponentSchema FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Sprite2DComponentSchemaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEXTURE_NAME = 4
  };
  const ::flatbuffers::String *texture_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTURE_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TEXTURE_NAME) &&
           verifier.VerifyString(texture_name()) &&
           verifier.EndTable();
  }
};

struct Sprite2DComponentSchemaBuilder {
  typedef Sprite2DComponentSchema Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_texture_name(::flatbuffers::Offset<::flatbuffers::String> texture_name) {
    fbb_.AddOffset(Sprite2DComponentSchema::VT_TEXTURE_NAME, texture_name);
  }
  explicit Sprite2DComponentSchemaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Sprite2DComponentSchema> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Sprite2DComponentSchema>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Sprite2DComponentSchema> CreateSprite2DComponentSchema(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> texture_name = 0) {
  Sprite2DComponentSchemaBuilder builder_(_fbb);
  builder_.add_texture_name(texture_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Sprite2DComponentSchema> CreateSprite2DComponentSchemaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *texture_name = nullptr) {
  auto texture_name__ = texture_name ? _fbb.CreateString(texture_name) : 0;
  return LeaderEngine::CreateSprite2DComponentSchema(
      _fbb,
      texture_name__);
}

inline const LeaderEngine::Sprite2DComponentSchema *GetSprite2DComponentSchema(const void *buf) {
  return ::flatbuffers::GetRoot<LeaderEngine::Sprite2DComponentSchema>(buf);
}

inline const LeaderEngine::Sprite2DComponentSchema *GetSizePrefixedSprite2DComponentSchema(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<LeaderEngine::Sprite2DComponentSchema>(buf);
}

inline bool VerifySprite2DComponentSchemaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<LeaderEngine::Sprite2DComponentSchema>(nullptr);
}

inline bool VerifySizePrefixedSprite2DComponentSchemaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<LeaderEngine::Sprite2DComponentSchema>(nullptr);
}

inline void FinishSprite2DComponentSchemaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LeaderEngine::Sprite2DComponentSchema> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSprite2DComponentSchemaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LeaderEngine::Sprite2DComponentSchema> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace LeaderEngine

#endif  // FLATBUFFERS_GENERATED_SPRITE2DCOMPONENTSCHEMA_LEADERENGINE_H_
