// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRANSFORMSCHEMA_LEADERENGINE_H_
#define FLATBUFFERS_GENERATED_TRANSFORMSCHEMA_LEADERENGINE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace LeaderEngine {

struct vec2;

struct TransformSchema;
struct TransformSchemaBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  vec2()
      : x_(0),
        y_(0) {
  }
  vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(vec2, 8);

struct TransformSchema FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransformSchemaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ROTATION = 6,
    VT_SCALE = 8
  };
  const LeaderEngine::vec2 *position() const {
    return GetStruct<const LeaderEngine::vec2 *>(VT_POSITION);
  }
  float rotation() const {
    return GetField<float>(VT_ROTATION, 0.0f);
  }
  const LeaderEngine::vec2 *scale() const {
    return GetStruct<const LeaderEngine::vec2 *>(VT_SCALE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<LeaderEngine::vec2>(verifier, VT_POSITION, 4) &&
           VerifyField<float>(verifier, VT_ROTATION, 4) &&
           VerifyField<LeaderEngine::vec2>(verifier, VT_SCALE, 4) &&
           verifier.EndTable();
  }
};

struct TransformSchemaBuilder {
  typedef TransformSchema Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const LeaderEngine::vec2 *position) {
    fbb_.AddStruct(TransformSchema::VT_POSITION, position);
  }
  void add_rotation(float rotation) {
    fbb_.AddElement<float>(TransformSchema::VT_ROTATION, rotation, 0.0f);
  }
  void add_scale(const LeaderEngine::vec2 *scale) {
    fbb_.AddStruct(TransformSchema::VT_SCALE, scale);
  }
  explicit TransformSchemaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TransformSchema> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TransformSchema>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TransformSchema> CreateTransformSchema(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const LeaderEngine::vec2 *position = nullptr,
    float rotation = 0.0f,
    const LeaderEngine::vec2 *scale = nullptr) {
  TransformSchemaBuilder builder_(_fbb);
  builder_.add_scale(scale);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  return builder_.Finish();
}

inline const LeaderEngine::TransformSchema *GetTransformSchema(const void *buf) {
  return ::flatbuffers::GetRoot<LeaderEngine::TransformSchema>(buf);
}

inline const LeaderEngine::TransformSchema *GetSizePrefixedTransformSchema(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<LeaderEngine::TransformSchema>(buf);
}

inline bool VerifyTransformSchemaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<LeaderEngine::TransformSchema>(nullptr);
}

inline bool VerifySizePrefixedTransformSchemaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<LeaderEngine::TransformSchema>(nullptr);
}

inline void FinishTransformSchemaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LeaderEngine::TransformSchema> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTransformSchemaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LeaderEngine::TransformSchema> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace LeaderEngine

#endif  // FLATBUFFERS_GENERATED_TRANSFORMSCHEMA_LEADERENGINE_H_
